jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew :module:assembleRelease
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: Zygisk-Il2CppDumper
          path: out/*.zip
